# Site settings
title: Jarrale Butts CS-499 ePortfolio
description: Check out my journey to creating my ePortfolio/MERN full-stack web app Capstone Project.
url: "https://tekibotzeportfolio.github.io"

# Markdown options
markdown: kramdown

# Theme settings (Jekyll theme)
#theme: jekyll-theme-hacker

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
