# Site settings
title: TekiBotz ePortfolio
description: Thanks for stopping by my personal portfolio site, my name is Jarrale Butts and I'm a Cyber Security Professional/Software Engineer. Check out my latest project.
url: "https://tekibotz.github.io"

# Markdown options
markdown: kramdown

# Theme settings (Jekyll theme)
#theme: jekyll-theme-hacker

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
